language: elixir
elixir:
- 1.6
otp_release:
- 20.2
addons:
  postgresql: '9.6'
cache:
  directories:
  - _build
  - deps
  - frontend/node_modules
before_install:
- nvm install --lts
- nvm use --lts
- cd frontend
- npm install
- cd ..
script:
- mix test
- cd frontend
- npm run unit
branches:
  only:
  - master
  - develop
deploy:
  provider: heroku
  api_key:
    secure: YGWPwkEq+zEIqjLMl69rh7lK2tWMrbapLmUUDHMBr2G8qxWvMdI1UbO+v9LTi1Exms8uuWTEtZHj1Sv28rjxQ2N+dmYGppLoHvqIputMycq0bV26snFrelJRsOoMvYSzkzkO94sCxUOAAK5o2k8iis8bM6yHW8i3TZGhJYb62SqIFPQS/nkDs/9Z+G5p0SgDjJ009s5AB9Porp7qCqO2X2kkNsyLvruIjvAJEVnSS0jbFOfoUUYt2amAZtf16AWM3GHVRkJcgvleoWxcnxbRTKFlE58HADlXcpNyITrIAxWIWDOEBfZEh10x/5UaT6HGDJSPZRn9NncF03IQkrDR60bbYG/ZOnWH+SzbDxvtio0ngnmAmqLbcrp1NaSB6phBax6CJXkpcXT1koHfwhmg27ubCGJQxLnRzlehsFwgSPKrSmfXFfv3NawDKpJt4otyMKuxIQcbuYJ3wu9sXq275GKIjcS2M9U7jfFNnJZghvWD4aA2SQc4YbOXSm3nhBm8m54/xfYIX/L82GjbqqXFv4JO8a52r2V9Lrh1gUBwmE9EwXgIx2rYSayFxXcIMuDdxpBdGq+meX2EIH9NfINCB2zJs6ps+doX0aKr9hrOZx2hDc8oYlOZMhyU0X5w6+BYPxe5KMMFrM/n8SkXzPhTBgUpMU9dQeyoAUcKAG9NT6c=
  app: nashville-zone-lookup
  # Migrations
  run: "mix ecto.migrate"
  strategy: git
