language: elixir

elixir:
  - 1.5.2

otp_release:
  - 20.1.3

cache:
  directories:
    - _build
    - deps
    - frontend/node_modules

before_install:
  # for e2e testing using Chrome and Selenium
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # install and use latest NodeJS LTS release
  - nvm install --lts
  - nvm use --lts
  # install frontend dependencies
  - cd frontend
  - npm install
  - cd ..

script:
  # test backend
  - mix test
  # test frontend
  - cd frontend
  - npm run test

branches:
  only:
    - master
    - develop

addons:
  chrome: stable
