language: elixir

elixir:
  - 1.5.1

otp_release:
  - 20.0.4

sudo: required
dist: trusty

before_install:
  # - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # - sudo apt-get update
  # - sudo apt-get install -y libappindicator1 fonts-liberation
  # - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  # - sudo dpkg -i google-chrome*.deb
  - nvm install --lts
  - nvm use --lts
  - cd frontend
  - npm install
  - cd ..

before_script:
  - jdk_switcher use oraclejdk8

script:
  - mix test
  - cd frontend
  - npm run unit
  - npm run e2e

branches:
  only:
    - master
    - develop
    - temp/setup-travis

addons:
  chrome: stable
