export const GET_INTENDED_USES_SUCCESS = 'GET_INTENDED_USES_SUCCESS'
export const GET_INTENDED_USES_FAILURE = 'GET_INTENDED_USES_FAILURE'
export const GET_USES_FOR_ADDRESS_SUCCESS = 'GET_USES_FOR_ADDRESS_SUCCESS'
